name: pi_puc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_getit: ^3.0.1
  loading_animation_widget: ^1.2.1
  asyncstate: ^2.1.1-dev.1
  shared_preferences: ^2.3.3
  signals_flutter: ^5.5.1
  top_snackbar_flutter: ^3.1.0
  validatorless: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
